services:
  dump1090:
    image: henkez/dump1090:test
    expose:
      - 8080
      - 30001
      - 30002
      - 30003
      - 30004
      - 30005
      - 30104
    ports:
      - 8080:8080
    restart: unless-stopped
  fr24feed:
    image: henkez/fr24feed:test
    depends_on:
      - dump1090
    expose:
      - 8754
    ports:
      - 8754:8754
    restart: unless-stopped
    volumes:
      - './config/fr24feed.ini:/etc/fr24feed.ini:ro'
