services:
  dump1090:
    image: henkez/dump1090:9.0-r2
    privileged: true
    restart: unless-stopped
  fr24feed:
    image: henkez/fr24feed:1.0.48-0
    depends_on:
      - dump1090
    ports:
      - 8754:8754
    restart: unless-stopped
    volumes:
      - ./config/fr24feed.ini:/etc/fr24feed.ini:ro